import React from 'react';
export const metadata = {
    title: " Blog App",
    description: "Generated by create next app",
  };


const blog = () => {
    return (
        <div>
            <h1> blog page</h1>
        </div>
    );
};

export default blog;